model_list:
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
